### ISSUE TITLE
Error trying to run opendatacam without docker (jetson nano)

### ISSUE THREAD

**Issue by osfa** [opendatacam/opendatacam#125] opened 2019-09-17 19:28 UTC
trying to follow [this](https://opendatacam.github.io/opendatacam/documentation/USE_WITHOUT_DOCKER.html
) on jetson nano.

getting error on npm start: "Please specify the path to the raw detections file"
found some old threads about ffmpeg? installed ffmpeg3. no luck.

something with a wrong path in config?
where do the "raw detections file" need to be? what is it? darknet seems to run fine.

`"NEURAL_NETWORK": "yolov3",
"PATH_TO_YOLO_DARKNET": "/home/myuser/darknet",`

weights are in `/home/myuser/darknet/yolov3.weights`

thx.

**Comment by tdurand** [comment] 2019-09-17 19:41
Hi, 

Could you paste the full output error ?

Did you run `npm run build` before `npm run start`

I can confirm that ffmpeg is not the issue, since ODC v2.0 we do no rely on it

Thanks

**Comment by tdurand** [comment] 2019-09-17 19:44
PS: _"Please specify the path to the raw detections file"_ isn't a meaningful error, you can ignore it. (It is there because of the node-moving-things package that just print this... need to be fixed)

**Comment by osfa** [comment] 2019-09-17 20:20
not sure. if I run on yolov3 it just freezes. if I use yolov3-tiny it just spews out 'stream stopped! 
' and then "Video-stream stopped!" until I ctrl+c out. been trying to get a better error message for you for awhile now but no luck..

**Comment by osfa** [comment] 2019-09-17 20:23
aha. ok the demo video is not in the repo like for the docker install...

**Comment by osfa** [comment] 2019-09-17 20:28
trying with raspberrycam_no_docker now.

getting:

` JSON-strError with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON`

mixed in with some

`FPS:13.2
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:12.7
 MJPEG-stream sent. 
Objects:`

but after awhile it is just

`Error with message send by YOLO, not valid JSON`

I have verified that raspberrycam works as per documentation.

**Comment by osfa** [comment] 2019-09-17 20:35
```
> Ready on http://localhost:8080
> Ready on http://192.168.1.9:8080
Success init db
Send request to connect to YOLO JSON Stream
Process YOLO started
{ OPENDATACAM_VERSION: [32m'2.0.0'[39m,
  PATH_TO_YOLO_DARKNET: [32m'/home/jbe/darknet'[39m,
  VIDEO_INPUT: [32m'raspberrycam_no_docker'[39m,
  NEURAL_NETWORK: [32m'yolov3-tiny'[39m,
  VIDEO_INPUTS_PARAMS:
   { file: [32m'opendatacam_videos/demo.mp4'[39m,
     usbcam:
      [32m'v4l2src device=/dev/video0 ! video/x-raw, framerate=30/1, width=640, height=360 ! videoconvert ! appsink'[39m,
     experimental_raspberrycam_docker:
      [32m'v4l2src device=/dev/video2 ! video/x-raw, framerate=30/1, width=640, height=360 ! videoconvert ! appsink'[39m,
     raspberrycam_no_docker:
      [32m'nvarguscamerasrc ! video/x-raw(memory:NVMM),width=1280, height=720, framerate=30/1, format=NV12 ! nvvidconv ! video/x-raw, format=BGRx, width=640, height=360 ! videoconvert ! video/x-raw, format=BGR ! appsink'[39m,
     remote_cam:
      [32m'YOUR IP CAM STREAM (can be .m3u8, MJPEG ...), anything supported by opencv'[39m },
  VALID_CLASSES: [ [32m'*'[39m ],
  DISPLAY_CLASSES:
   [ { class: [32m'bicycle'[39m, icon: [32m'1F6B2.svg'[39m },
     { class: [32m'person'[39m, icon: [32m'1F6B6.svg'[39m },
     { class: [32m'truck'[39m, icon: [32m'1F69B.svg'[39m },
     { class: [32m'motorbike'[39m, icon: [32m'1F6F5.svg'[39m },
     { class: [32m'car'[39m, icon: [32m'1F697.svg'[39m },
     { class: [32m'bus'[39m, icon: [32m'1F68C.svg'[39m } ],
  PATHFINDER_COLORS:
   [ [32m'#1f77b4'[39m,
     [32m'#ff7f0e'[39m,
     [32m'#2ca02c'[39m,
     [32m'#d62728'[39m,
     [32m'#9467bd'[39m,
     [32m'#8c564b'[39m,
     [32m'#e377c2'[39m,
     [32m'#7f7f7f'[39m,
     [32m'#bcbd22'[39m,
     [32m'#17becf'[39m ],
  COUNTER_COLORS:
   { yellow: [32m'#FFE700'[39m,
     turquoise: [32m'#A3FFF4'[39m,
     green: [32m'#a0f17f'[39m,
     purple: [32m'#d070f0'[39m,
     red: [32m'#AB4435'[39m },
  NEURAL_NETWORK_PARAMS:
   { yolov3:
      { data: [32m'cfg/coco.data'[39m,
        cfg: [32m'cfg/yolov3.cfg'[39m,
        weights: [32m'yolov3.weights'[39m },
     [32m'yolov3-tiny'[39m:
      { data: [32m'cfg/coco.data'[39m,
        cfg: [32m'cfg/yolov3-tiny.cfg'[39m,
        weights: [32m'yolov3-tiny.weights'[39m },
     [32m'yolov2-voc'[39m:
      { data: [32m'cfg/voc.data'[39m,
        cfg: [32m'cfg/yolo-voc.cfg'[39m,
        weights: [32m'yolo-voc.weights'[39m } },
  TRACKER_ACCURACY_DISPLAY:
   { nbFrameBuffer: [33m300[39m,
     settings:
      { radius: [33m3.1[39m,
        blur: [33m6.2[39m,
        step: [33m0.1[39m,
        gradient: [36m[Object][39m,
        canvasResolutionFactor: [33m0.1[39m } },
  MONGODB_URL: [32m'mongodb://127.0.0.1:27017'[39m }
layer     filters    size              input                output
   0 (node:7783) [DEP0001] DeprecationWarning: OutgoingMessage.flush is deprecated. Use flushHeaders instead.
Send request to connect to YOLO JSON Stream
First request on console stream
Send request to connect to YOLO JSON Stream
conv     16  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  16 0.150 BF
   1 max          2 x 2 / 2   416 x 416 x  16   ->   208 x 208 x  16 0.003 BF
   2 conv     32  3 x 3 / 1   208 x 208 x  16   ->   208 x 208 x  32 0.399 BF
   3 max          2 x 2 / 2   208 x 208 x  32   ->   104 x 104 x  32 0.001 BF
   4 conv     64  3 x 3 / 1   104 x 104 x  32   ->   104 x 104 x  64 0.399 BF
   5 max          2 x 2 / 2   104 x 104 x  64   ->    52 x  52 x  64 0.001 BF
   6 conv    128  3 x 3 / 1    52 x  52 x  64   ->    52 x  52 x 128 0.399 BF
   7 max          2 x 2 / 2    52 x  52 x 128   ->    26 x  26 x 128 0.000 BF
   8 conv    256  3 x 3 / 1    26 x  26 x 128   ->    26 x  26 x 256 0.399 BF
   9 max          2 x 2 / 2    26 x  26 x 256   ->    13 x  13 x 256 0.000 BF
  10 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512 0.399 BF
  11 max          2 x 2 / 1    13 x  13 x 512   ->    13 x  13 x 512 0.000 BF
  12 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024 1.595 BF
  13 conv    256  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 256 0.089 BF
  14 conv    512  3 x 3 / 1    13 x  13 x 256   ->    13 x  13 x 512 0.399 BF
  15 conv    255  1 x 1 / 1    13 x  13 x 512   ->    13 x  13 x 255 0.044 BF
  16 yolo
[yolo] params: iou loss: mse, iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
  17 route  13
  18 conv    128  1 x 1 / 1    13 x  13 x 256   ->    13 x  13 x 128 0.011 BF
  19 upsample            2x    13 x  13 x 128   ->    26 x  26 x 128
  20 route  19 8
  21 conv    256  3 x 3 / 1    26 x  26 x 384   ->    26 x  26 x 256 1.196 BF
  22 conv    255  1 x 1 / 1    26 x  26 x 256   ->    26 x  26 x 255 0.088 BF
  23 yolo
[yolo] params: iou loss: mse, iou_norm: 0.75, cls_norm: 1.00, scale_x_y: 1.00
Total BFLOPS 5.571 
 Allocate additional workspace_size = 52.43 MB 
Loading weights from yolov3-tiny.weights...Demo
Done!
Send request to connect to YOLO JSON Stream
Send request to connect to YOLO JSON Stream
Error with message send by YOLO, not valid JSON

 seen 64 
video file: nvarguscamerasrc ! video/x-raw(memory:NVMM),width=1280, height=720, framerate=30/1, format=NV12 ! nvvidconv ! video/x-raw, format=BGRx, width=640, height=360 ! videoconvert ! video/x-raw, format=BGR ! appsink
GST_ARGUS: Creating output stream
CONSUMER: Waiting until producer is connected...
GST_ARGUS: Available Sensor modes :
GST_ARGUS: 3264 x 2464 FR = 21.000000 fps Duration = 47619048 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 3264 x 1848 FR = 28.000001 fps Duration = 35714284 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1920 x 1080 FR = 29.999999 fps Duration = 33333334 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1280 x 720 FR = 59.999999 fps Duration = 16666667 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1280 x 720 FR = 120.000005 fps Duration = 8333333 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: Running with following settings:
   Camera index = 0 
   Camera mode  = 4 
   Output Stream W = 1280 H = 720 
   seconds to Run    = 0 
   Frame Rate = 120.000005 
GST_ARGUS: PowerService: requested_clock_Hz=6048000
GST_ARGUS: Setup Complete, Starting captures for 0 seconds
GST_ARGUS: Starting repeat capture requests.
CONSUMER: Producer has connected; continuing.
Video stream: 640 x 360 
Objects:

 JSON-stream sent. 

FPS:0.0
Objects:

 JSON-stream sent. 

FPS:-0.0
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.1
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.0
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.0
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.3
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.3
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.2
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.3
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.3
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.1
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.1
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.0
 MJPEG-stream sent. 
Objects:

JSON_sender: new client 49
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
New client, close previous stream
Error with message send by YOLO, not valid JSON
New client, close previous stream
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
 JSON-stream sent. 

FPS:9.6
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.6
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.4
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.2
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.2
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.2
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.4
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.5
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:9.6
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.3
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.0
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.6
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:15.6
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:15.8
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.6
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.3
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.7
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.5
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.0
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.5
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.2
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:9.9
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.3
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.0
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:9.9
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.4
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:12.5
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:12.1
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:9.7
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:11.8
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.0
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:9.7
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:10.3
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:12.9
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:12.7
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:14.4
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.5
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:12.3
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:11.9
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:14.1
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.3
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.8
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.4
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.5
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.1
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:12.9
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:14.5
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:12.8
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.0
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.5
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.0
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.1
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.1
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.6
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.6
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.1
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.5
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.2
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.4
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.6
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.3
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.2
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.4
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.4
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.0
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.5
 MJPEG-stream sent. 
Objects:

 JSON-stream sent. 

FPS:13.9
 MJPEG-stream sent. 
Objects:

 JSON-stream seError with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
Error with message send by YOLO, not valid JSON
```

**Comment by osfa** [comment] 2019-09-17 20:48
I'm having a really hard time gauging whether something is broken or not. The Nano really chokes and sometimes everything slows to a crawl. I'm running with a monitor is that the issue? Is this message not an actual error message with the app? Found something about that in #70 

I never get to the actual application screen on localhost:8080 anyway, just the load screen.

**Comment by tdurand** [comment] 2019-09-17 21:08
Some comments:

- On jetson nano, you should run `yolov3-tiny` , otherwise nano doesn't have the power to run other weights

- From your output, seems everything is working fine, maybe the issue is that it doesn't detect any object.. have you tried to point the cam at your face ? 

Maybe you can try to run on the demo file to make sure this is the issue, in order to do so:

- create an `opendatacam_videos` folder in your darknet repo , and download inside this video: https://github.com/opendatacam/opendatacam/blob/master/static/demo/demo.mp4

- set VIDEO_INPUT to "file" in your config.json

- `npm build; npm start;`

If this works, the issue would be with the cam.

**Comment by tdurand** [comment] 2019-09-17 21:12
Also yes, running with a monitor causes big slowdown... That is why we recommend doing the setup and then connecting to opendatacam ui from an external device in the "docker" guide: https://github.com/opendatacam/opendatacam/blob/master/documentation/jetson/JETSON_NANO.md

But you could SSH into your jetson nano from another devices and run the commands from there also

**Comment by tdurand** [comment] 2019-09-23 13:55
Have you been able to solve this ? Closing but feel free to reopen

**Closed by tdurand** 2019-09-23 13:55 UTC
Labels: question

**Comment by collabnix** [comment] 2020-01-10 07:39
Yes, this error occur when YOLO doesnt detect any object. I tried pointing my USB cam to very lowest light it failed to detect object. As soon as I put it in bright area, it worked without any error message.
